name: NinjaHeroes Daily Claim Automate

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Menjadwalkan untuk menjalankan setiap hari pada tengah malam UTC

jobs:
  claim_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode sumber dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Firefox dan GeckoDriver
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.32.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      # Set environment variables for Telegram Bot
      - name: Set Telegram Bot Token and Chat ID
        run: echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          
      - name: Set Telegram Chat ID
        run: echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      # Run Python script to perform the claim
      - name: Run claim script
        run: |
          python sc.py  # Ganti dengan nama file skrip Python Anda
