name: KageHero Claim Bot

on:
  schedule:
    - cron: "0 */6 * * *"  # Menjalankan setiap 6 jam
  workflow_dispatch:  # Menambahkan trigger manual jika ingin menjalankan kapan saja


jobs:
  claim-items:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Menyesuaikan dengan versi Python yang diinginkan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          chmod +x ./drivers/geckodriver

      - name: Run claim script
        run: |
          python ./scripts/claim_script.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
